### ISSUE TITLE
Problem importing an openAstronomylog file from skySafari

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#672]
[ObservingLogsOAL.xml.txt](https://github.com/DeepskyLog/DeepskyLog/files/1618698/ObservingLogsOAL.xml.txt)
Hi,

I exported the attached from SkySafari and straight up tried to import in DSL bit I get the "Invalid XML file".

Any assistance would be most welcome!

Clear skies,

Nicos Kountouris

**Comment by WimDeMeester** [comment]
Thanks Wim!

This is a "vanilla" file just as it came out from LiveSky. If there is an export problem from SkySafari, hopefully it can be fixed on their end.

I have also posted on their online forums.

Clear skies,

Nicos

**Comment by WimDeMeester** [comment]
The topic on the skySafari forum:

https://support.simulationcurriculum.com/hc/en-us/community/posts/115010580588-DeepSkyLog-rejects-OAL-format-of-LiveSky

**Comment by WimDeMeester** [comment]
The file also can not be read in Observation Manager, see 

http://observation.sourceforge.net/en/

So, it looks like there is a problem with the skysafari file...

**Comment by WimDeMeester** [comment]
There are some problems with the XML file, the discussion can be followed on the skySafari forum. 

Some problems were also found in the DeepskyLog code to import the XML files, so an update is needed.

**Comment by WimDeMeester** [comment]
We need #673 to be able to import the targets.

**Comment by WimDeMeester** [comment]
DeepskyLog part fixed in #673

**Comment by TomCorstjens** [comment]
Complaint from user (via email): 
I am not able to import .xml open astronomy log from SkySafari LiveSky. Saying invalid xml format.
Thanks
Shawn Grant

**This relates to an existing issue that appears not completely resolved. 
Re-opening issue.**

**Comment by WimDeMeester** [comment]
The export of observations from SkySafari LiveSky still produces corrupt OAL/XML files. However, I changed the code to work around that. It should be possible now to import the corrupt XML files.
